### ISSUE TITLE
Importing Medications

### ISSUE THREAD

**Issue by fgiorlando** [HospitalRun/hospitalrun-frontend#1010]
Is there a means of using the DB import to import medications?
Specifically, I am hoping to import the Australian PBS database of medications (see here for plain text and xml versions: http://www.pbs.gov.au/browse/downloads).

I have had a look at the sample-data.txt which imports a singe drug (Cefazolin), but I'm not sure how to get a list of medications imported.
I'm comfortable with used sed to mangle the text file into shape, just wanting some tips on how to get started...

**Comment by jkleinsc** [comment]
@fgiorlando if you are looking to import medication (or other types of inventory), I would recommend using our import tool for inventory documented here:
https://github.com/HospitalRun/hospitalrun-server/blob/master/README.md#inventory-import

Basically if you can provide the information in a CSV file, you can import it into HospitalRun.

**Comment by zeigerpuppy** [comment]
Thanks @jkleinsc, I'll give that a go.  Would it be useful to your users if I post the modified .CSV once I get it working?  The PBS listing includes all the government approved drugs in Australia so is quite an extensive list that may be useful to others.

**Comment by jkleinsc** [comment]
@zeigerpuppy, it would be great if you could share your work.  Thanks!

**Comment by dmkar333** [comment]
There is also RxNorm, which seems to be a US equivilent to PBS.  It can also be used to check for potential for drug-drug interactions when prescribing medicine.

Their site: https://www.nlm.nih.gov/research/umls/rxnorm/ 

They have monthly updates and the download are text files that come with mysql and oracle load scripts.  Been a while since I have done it, but it wasn't too hard if memory serves.  We didn't use it for the drug-drug interaction  functionality though, just the medicine name / description.

**Comment by tangollama** [comment]
@zeigerpuppy any update on this issue?

**Comment by zzbazinga** [comment]
Hello I am newbie here, can I help in this regards??

**Comment by epolicardo** [comment]
@tangollama @jkleinsc I'm not found inv-import.js file under utils folder, or any other folder. Please can help me?

**Comment by jkleinsc** [comment]
@epolicardo it is part of the hospitalrun-server project: https://github.com/HospitalRun/hospitalrun-server/blob/master/utils/inv-import.js

**Comment by SamuelOkebaram** [comment]
How can I add bulk users in this application
