### ISSUE TITLE
A button for switch between language...

### ISSUE THREAD

**Issue by jujes** [HospitalRun/hospitalrun-frontend#1094]
**Expected behavior:**
option to switch from English to Spanish
**Actual behavior:**
No Spanish language as choice

Hi, someone know how I can make available the Spanish has a choice for user interface?

thanks in advance,

**Comment by tangollama** [comment]
Thanks @jujes. This is a missing feature and one that someone in the community could (relatively) quickly tackle. I'll label appropriately.

**Comment by wildaces215** [comment]
Iss this open I would like to look into it!

**Comment by wildaces215** [comment]
I look into this!

**Comment by richiethomas** [comment]
Should the language settings be stored as an attribute of the user, so they persist with each user session?

**Comment by tangollama** [comment]
A global config for the default and a user preference are in order. 

Typed or dictated imperfectly on my iPhone (717.385.9970)

**Comment by tchan** [comment]
@richiethomas 
Hopefully these links will be helpful, although I am unsure
https://eviltrout.com/2013/11/24/i18n-in-ember.html
https://github.com/jamesarosen/ember-i18n

**Comment by richiethomas** [comment]
@tchan yeah looks like that's currently a dependency of the project.  I'll definitely need to read through the package documentation as part of playing the story.

@tangollama since there's no design spec to work off, is there a certain location where the language toggle should go?  Or should I just come up with something and submit it for consideration?  My first thought was adding a select element to the dropdown that appears when clicking the "Settings" gear.

**Comment by tangollama** [comment]
I think that's a great recommendation on the gear location. Perhaps @jglovier can offer some guidance as well.

**Comment by richiethomas** [comment]
Thanks @tangollama.  Follow-up question- in the past I've used an npm package called `ember-power-select` for use cases like this.  It's powerful and well-maintained.  I'm thinking about using it in the implementation of the language select dropdown, but since it would be a new dependency I wanted to run it by y'all first.

More info here- https://github.com/cibernox/ember-power-select

**Comment by jkleinsc** [comment]
@richiethomas I would prefer to not add another select component to the project.  We currently use ember-rapid-forms which has a select component (em-select) and there also is a another component, ember-select-list, in the project.

**Comment by richiethomas** [comment]
@jkleinsc gotcha, wasn't aware of those other 2 dependencies.  I'll investigate those instead.

**Comment by richiethomas** [comment]
@jkleinsc I'm running into problems with the navigation.js mixin.  When I toggle the language in my dropdown menu, the change propogates to the i18n service, which causes all the relevant components to re-render except for the sidebar navigation.  This is because the text values for these elements are populated by the `localizedNavItems` property.  This bug occurs even when I add the `i18n` service as a dependency of the computed property (i.e. `localizedNavItems: Ember.computed('i18n', ...)`).

I don't see any authorization logic (i.e. `userCanDoFoobar`) inside this method, so I'm not sure what this method adds that we couldn't get from having the navItems key/value pairs in the translations files.  Any light you could shed on this would be appreciated.

**Comment by jkleinsc** [comment]
@richiethomas I think you need `Ember.computed('i18n.locale', ....)` instead of `Ember.computed('i18n', ....)`.

As far as localizedNavItems is concerned, it is an artifact to the way the navigation was localized.  I would be happy if we changed the navigation to define translation keys instead of text that gets automagically translated.  There really isn't a good reason for it being the way it is right now.

**Comment by richiethomas** [comment]
@jkleinsc yep, `i18n.locale` did the trick!  I now have a working version of the language toggle.  Just need tests to support it. :-)

As for `localizedNavItems`, I'm happy to refactor this out as part of this story.  Just to confirm, my understanding is that I should only need to move the `navItems` hash logic into the translations files, and then refactor the views to use the `t` helper method instead of this computed property.  Does that sound correct to you as well?

**Comment by jkleinsc** [comment]
@richiethomas That sounds correct to me.  I would also verify that there isn't anything funky in the tests with those, but I would just make the change and then just verify if the tests are passing.

**Comment by richiethomas** [comment]
@jkleinsc cool, thanks.  Going back to the `i18n` vs `i18n.locale` question for a second, this implies that Ember only watches for shallow changes to dependencies such as `i18n`, not deeply-nested changes.  I assume this is a feature in Ember, not a bug, but in my mind the most intuitive implementation would be to watch for deep changes (for this exact case as well as similar cases).  This implies that I'm missing some broader context that more seasoned devs like the Ember core team thought of.  Do you have a sense of why shallow seems to be the preferred implementation here, or am I better off asking Stack Overflow?  Let me know if I should rephrase my question.

**Comment by jkleinsc** [comment]
@richiethomas good question.  Yes, this is the way Ember works.  I think (my own 2c) there is a good reason why: computed properties are cached and are only recalculated when the dependent keys change.  If it went deep on an object every time *anything* changed on the object, that means that the computed property would be unnecessarily recalculated on every change, instead of just focusing on the changes that the computed property depended on.  If you had a rather large object you could up needlessly recalculating endlessly.

Having said that, there is a way in Ember to work with aggregate data in computed properties:
https://guides.emberjs.com/v2.13.0/object-model/computed-properties-and-aggregate-data/

**Comment by richiethomas** [comment]
Awesome, that makes sense now.  Thanks for that, and I'll take a look at the link.

**Comment by richiethomas** [comment]
@jkleinsc since the code for this feature has been solely on my machine for awhile, I'd like to try to get the initial version (before refactoring out the `localizedNavItems` method) up to a branch for a review (and possibly a merge?).  I find it more manageable to get code reviews for smaller chunks of code in stages, and this way if you decide to merge it, the feature is available to users sooner.  How does that sound?  NB: I'm still writing tests for the feature but I'm making progress on them.

**Comment by jkleinsc** [comment]
@richiethomas I wholeheartedly agree.  Smaller PRs are much easier to review.

**Comment by richiethomas** [comment]
<img width="1440" alt="before clicking the gear" src="https://user-images.githubusercontent.com/3839713/27457911-795b50e4-5774-11e7-98e8-6dda7d513c6a.png">
<img width="1440" alt="clicking the gear and seeing the dropdown" src="https://user-images.githubusercontent.com/3839713/27457915-7b2e9e80-5774-11e7-9052-2b29be5ce7c1.png">
<img width="1440" alt="selecting a language" src="https://user-images.githubusercontent.com/3839713/27457917-7f8cfb20-5774-11e7-8501-6a7c0db080a7.png">
<img width="1440" alt="language changed from english to french note the change in sidebar and table header translations but page title has not changed" src="https://user-images.githubusercontent.com/3839713/27457929-85335f2e-5774-11e7-9a02-aec034b9471c.png">
<img width="1440" alt="after page refresh page title has changed too" src="https://user-images.githubusercontent.com/3839713/27457932-87843f1e-5774-11e7-897b-46198e31b344.png">

**Comment by richiethomas** [comment]
P.S.- ignore the `<script>alert("Hi")</script>` in the Patient Name column.  I was doing some security testing. :-p

**Comment by richiethomas** [comment]
To address the original issue that prompted @jujes to report this- the `locales/es/translations.js` file is missing quite a few of the values required to have a first-class Spanish-language version of the app.  I could probably go on Google Translate and fill in the missing blanks, but I don't think that would do the app or the language justice.  Given the worst-case scenario of a mis-translation in a medical app such as this, a native Spanish speaker should probably take on that work instead.  @jkleinsc what are your thoughts?

**Comment by jkleinsc** [comment]
@richiethomas missing translations should be filed as separate issues so that we can solicit folks with good understanding of the language to be translated to work on them.

**Comment by jkleinsc** [comment]
Resolved by #1109.

**Comment by tchan** [comment]
I know that the translation files need a lot to be added but I just found the missing translations for the dropdown to be a bit strange. Like so
![gif](http://i.imgur.com/fI0TG2U.gif)

I had a bit of time tonight so I'll try to contribute :)

**Comment by tchan** [comment]
Also while playing around with the dropdown selector for the language. I kept accidentally click the logout button. You can select it even though if you are not directly hovering over the text (pic below) which makes for an unideal user experience.
![](https://puu.sh/wQQwv.png)
