### ISSUE TITLE
Add photos specifically to a procedure and visit

### ISSUE THREAD

**Issue by tangollama** [HospitalRun/hospitalrun-frontend#1106]
**Expected behavior:**
Currently, the system supports attaching multiple photos to a patient, but there's no granularity down to the Visit or Procedure level. Attaching photos to a visit and procedure and having them specifically surface in those interfaces would be preferable from a usability standpoint.

**Actual behavior:**
Currently, photos are attached only to patients and not (optionally) categorized by visit or procedure.

- [ ] Add optional meta data to photos that allow visit and procedure ID's to be added by the system
- [ ] Add photo uploads to the Visit screen
- [ ] Add photo display to the Visit screen
- [ ] Add photo uploads to the Procedure screen
- [ ] Add photo display to the Procedure screen

**Steps to reproduce:**
N/A

**Screenshots (if applicable):**
N/A

**OS and Browser:**
N/A

**Comment by ArtificialQualia** [comment]
@tangollama I'd like to work on this.

I've been playing around with the code base the past few days and now have the confidence I could add this.

From a functionality standpoint, do we want uploads through the Visits and Procedure screen to also attach the patient ID so that those photos are retrieved in both the Visits/Procedure screen AND the patient's photo screen?
