### ISSUE TITLE
Login as Social Worker - Make new appointment - Start Date 

### ISSUE THREAD

**Issue by SaiBabajiAnanda** [HospitalRun/hospitalrun-frontend#1123]
Steps to replicate :
 Login as Social Worker
 Click Add Appointments under Scheduling tab
 Select a patient name
 Select Start Date

Expected Result:
 Past date should be disabled
 Actual Result
 System allows past date to be selected for making new appointments

Browser : IE
 Screenshot attached
![new appointment - start date](https://user-images.githubusercontent.com/29377369/28138882-ea97de82-6717-11e7-8143-d082b0d82b03.jpg)

**Comment by santiago0697** [comment]
Hello @SaiBabajiAnanda 

What do you mean with "Past Date" i dont see that field on the picture, can you write the exact field label

Thanks

**Comment by SaiBabajiAnanda** [comment]
@santiago0697 on july 12th, system allowed to create appointment for june 15th. System allows to select past date in the 'Start Date' field to make new appointment.
Thanks
Vidhya

_Sent from my Samsung SM-G935T using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by tangollama** [comment]
@santiago0697 @SaiBabajiAnanda arguably, there could be a reason (for reporting purposes) someone might enter an appointment in the past. That said, can you offer a reason why the functionality as-is is harmful / irresponsible / unhelpful?

**Comment by tchan** [comment]
@tangollama I think the issue is more "it is not possible/logical that a user can make an appointment in the past" so it doesn't make sense that the option is available to the user.

In response to the reporting purposes, correct me if I'm wrong here (writing from memory), the appointment page uses the same date-picker component which should be able to take in a property which sets the mindate. Setting the mindate property here wouldn't affect the other reporting pages so you'd still be able to look at appointments in the past. That said, I'll take a closer look tonight.
