### ISSUE TITLE
Can't login on chrome brower and firefox brower. (safari is OK).

### ISSUE THREAD

**Issue by tamdaovssc** [HospitalRun/hospitalrun-frontend#1137]
**Expected behavior:**

**Actual behavior:**

**Steps to reproduce:**

**Screenshots (if applicable):**

**OS and Browser:**
Mac OS X 10.12.6 - Safari - Chrome - Firefox

**Comment by tamdaovssc** [comment]
Dear all
I have a problem. I build hospitalrun-frontend on Ubuntu server.
I login from another computer with Safari is Ok. So, Login on Chrome or Firefox is not Ok.
I included content="chorme=1" on index.html file. 
Could you help me?

**Comment by Primedi** [comment]
I had a similar problem. It occurred because I didn't allow history on Firefox.
So if you use private browsing it seems that the script "vendor.js" from /dist/assets doesn't work as it should.
As I'm new on github I'm not sure whether it works.

I hope that this works and that I understood the question correctly.

**Comment by tamdaovssc** [comment]
Dear Primedi

I run chrome with incognito mode and Firefox with private mode but not OK.
So, I'm new on coder and fresh Emberjs.
Thanks,

**Comment by Primedi** [comment]
Dear tamdaovssc,
maybe it is not OK because you run chrome with incognito mode and firefox with private mode.
If you get the "Loading"-preview try the inspector (on firefox) and try to figure out whether there is a failure that says "[...] maybe you run in a private mode". If there is a similar content, try to run e.g. firefox not with private mode to see, if thats ok. 

If there's not, you please try to find the error and share it with us, so we can work to fix it.
Every error-text can be helpful as it gives us a hint where the problem may be.

Hope that helped a little.
Kindest regards

**Comment by tangollama** [comment]
The system is really designed to run on Chrome. In general, it should work on Firefox, but there are some pieces that we're aware don't work on Safari (or at least some features on some versions of Safari). I'm unable to reproduce this. @tamdaovssc can you provide more detail?

**Comment by tamdaovssc** [comment]
Dear Tangollama

Run in Chrome and Firefox on localhost is OK. But, login from another PC (same LAN) it's not OK.
It run "no security" mode.
I used Ember Inspector and checking error.
![ember error](https://user-images.githubusercontent.com/29267761/29009687-e9c39ecc-7b14-11e7-817e-828e3b09be86.png)
Thanks,

**Comment by tamdaovssc** [comment]
Dear all

I check security issue for ember on link: https://github.com/ember-cli/ember-cli/issues/5123
I run ember s --host my IP.
It had only error: Error registering service worker:SecurityError: Only secure origins are allowed (see: https://goo.gl/Y0ZkNV).
(anonymous) @ (index):42
Promise rejected (async)
(anonymous) @ (index):41
 
Thanks

**Comment by tchan** [comment]
@tamdaovssc Can you post the full ember s command that you are using? Eg:
`ember s --proxy website`

**Comment by tchan** [comment]
I assume you're using
`ember s --proxy http://192.168.10.205:49152`

Have you also tried
`ember s --proxy https://192.168.10.205:49152`
?

**Comment by tamdaovssc** [comment]
Dear tchan

It is not fix.
Thanks and Regards,

**Comment by tchan** [comment]
@tamdaovssc Can you post the exact commands you've tried?

**Comment by tamdaovssc** [comment]
Dear tchan

I ran commands:
ember s --proxy http://192.168.10.205:49152

**Comment by fooksupachai** [comment]
1.Kill the Chrome Process from Task manager – Open Task Manager and Kill Every process of Google Chrome.
2. Reboot Your Computer and check again.
3. If your computer has another user account then log on to that account and check whether it is working or not, if chrome is working on another user account then first user account got affected, If it doesn’t work on any user account then chrome got affected for all users.

**Comment by nzidol** [comment]
Can be reproduced on Linux with docker, build and start docker containers. Check it works using localhost:4200 then find ip-address of container  `docker container inspect hospitalrun-frontend` and connect to ipaddress:4200 . You cannot get past the login screen, likely reason is security rules in Chrome that allow ws:// connections only to secured site or localhost and the docker container, or stand-alone install, have no ssl-cert at the moment.

**Comment by BogdanAlexandru** [comment]
Can repro by running HR+ in a VM and attempting to open it up in the host, with VM'sIP:port.

A "fix" for Chrome:

`chrome.exe --unsafely-treat-insecure-origin-as-secure="http://HRIP:PORT"`

Where `HRIP` is the IP address at which the HospitalRun server is located, and `PORT` is the port at which it listens.

Aside from this you may want to specify a custom `--user-data-dir=DATADIR` param, so that it keeps user data separate from your main browser's. For Linux that would look like `--user-data-dir=/home/user/hrchrome`, for Windows maybe something like `--user-data-dir=C:\hrchrome`.

May want to create something like a new shortcut to chrome.exe (on Windows) with the parameters above preset, so you can spawn it with one click. For Linux you can save the chrome invocation line to a shell script and run that.

**Comment by tangollama** [comment]
@tamdaovssc did @BogdanAlexandru's recommendation address your issue? If so, can you close this.
