### ISSUE TITLE
Prevent Random Lab Types & Imaging Types being created by users.

### ISSUE THREAD

**Issue by garylm** [HospitalRun/hospitalrun-frontend#1138]
**Expected behavior:**  On the New Lab Request forms: Lab Type / Imaging Type is a drop down that Should be Limited to the list of Billing Lab or Imaging types that actually show in the drop down. 

**Actual behavior:**  You can type randomly into the drop down field and save the request with anything for a request type.

********* This happens even if the related Lookup Lists are set to prevent user additions to the Lab Type or Imaging Type lists.

Examples:
[OWH Lab Type random 1.pdf](https://github.com/HospitalRun/hospitalrun-frontend/files/1180555/OWH.Lab.Type.random.1.pdf)
[OWH Lab Type random 2.pdf](https://github.com/HospitalRun/hospitalrun-frontend/files/1180557/OWH.Lab.Type.random.2.pdf)

**OS and Browser:** Both Chrome & Firefox, HR Docker based Server.

**Comment by tangollama** [comment]
Thanks @thai510 for looking into this.

**Comment by djstark** [comment]
@tangollama Hello, I've been looking at this problem but I'm new to JavaScript/Ember. The problem seems to be the validation for the imaging/lab input forms. I tried rewriting the validation to mimic how the patient/medication validations are done (which work as intended) but wasn't able to get it functioning. I'm stuck at the moment, so any guidance would be appreciated.

imaging input
```
      {{checkbox-or-typeahead property="imagingTypeName"
        label=(t 'labels.imagingType') list=objectTypeList
        selection=selectedImagingType
        optionLabelPath='name'
        typeAheadType='pricing'
        className="required"
        prompt=" "
        model=model
        class="imaging-type-input"
      }}
```
current imaging validation
```
  validations: {
    imagingTypeName: {
      presence: {
        'if'(object) {
          if (object.get('isNew')) {
            return true;
          }
        },
        message: 'Please select an imaging type'
      }
    }
```
Medication validation (works as intended and doesn't allow random user input)
```
    inventoryItemTypeAhead: {
      acceptance: {
        accept: true,
        if(object) {
          if (!get(object, 'hasDirtyAttributes') || !get(object, 'isNew')) {
            return false;
          }
          let itemName = get(object, 'inventoryItem.name');
          let itemTypeAhead = get(object, 'inventoryItemTypeAhead');
          if (Ember.isEmpty(itemName) || Ember.isEmpty(itemTypeAhead)) {
            // force validation to fail
            return true;
          } else {
            let typeAheadName = itemTypeAhead.substr(0, itemName.length);
            if (itemName !== typeAheadName) {
              return true;
            }
          }
          // Inventory item is properly selected; don't do any further validation
          return false;
        },
        message: 'Please select a valid medication'
      }
    }
```
reworked imaging validation mimicking patient/medication 
```
    imagingTypeName: {
      acceptance: {
        accept: true,
        if(object) {
          if (!get(object, 'hasDirtyAttributes') || !get(object, 'isNew')) {
            return false;
          }
          
          let imageName = get(object,'imagingPricingType.name');
          let imageTypeName = get(object,'imagingTypeName');

          if (Ember.isEmpty(imageName) || Ember.isEmpty(imageTypeName)) {
            // force validation to fail
            return true;
          }
          else {
            let typeAheadName = imageTypeName.substr(0, imageName.length);
            if (imageName !== typeAheadName) {
              return true;
            }
          }
          return false;
        },
        message: 'Please select an imaging type'
      }
    }
```

**Comment by fooksupachai** [comment]
All experimental uncertainty is due to either random errors or systematic errors. Random errors are statistical fluctuations (in either direction) in the measured data due to the precision limitations of the measurement device. Random errors usually result from the experimenter's inability to take the same measurement in exactly the same way to get exact the same number. Systematic errors, by contrast, are reproducible inaccuracies that are consistently in the same direction. Systematic errors are often due to a problem which persists throughout the entire experiment.

Note that systematic and random errors refer to problems associated with making measurements. Mistakes made in the calculations or in reading the instrument are not considered in error analysis. It is assumed that the experimenters are careful and competent!

**Comment by stukalin** [comment]
@thai510 did you have a chance to have a look on that? @djstark do you still need help with the issue? Would you be able to finish that?
