### ISSUE TITLE
Lab Custom Form fields do not appear in final OPD

### ISSUE THREAD

**Issue by KenyanGeek** [HospitalRun/hospitalrun-frontend#1176]
**Expected behavior:**
Custom fields data entered into Lab reports to appear in final OPD report
**Actual behavior:**
Added Custom Form fields do not appear in final OPD
**Steps to reproduce:**
--->Add Custom Form on Labs Module
---->Add data to the custom forms in the lab module
----->Generate an OPD report
**Screenshots (if applicable):**

**OS and Browser:**

**Comment by tangollama** [comment]
Similar to #1166 but more specific

**Comment by DerekTBrown** [comment]
@tangollama I am taking a look at this now.  It seems that  associating a custom form with a lab (or some other model) would require some changes to the model? Is that fair.

**Comment by stukalin** [comment]
Well that's an interesting one. I've started with custom form, it turned out that they do not work, so I tried to fix them etc. etc. And now when I've finally got working custom forms for labs I am stuck with the OPD report itself.

The thing is that when we generate a report we have the following code:
```
{{#each visit.labs as |item|}}
  <li class="test-labs-data">{{item.labType.name}}-{{item.result}} ({{item.status}})</li>
{{/each}}
```
which, as it's expected just prints out a list of texts:

![bildschirmfoto vom 2018-02-15 15-18-33](https://user-images.githubusercontent.com/9863365/36261323-4462882a-1264-11e8-8b07-6e01bb566b7d.png)

So, there were supposed no custom forms. And hence I've got a couple of questions:

@KenyanGeek we are talking about custom forms with type _Lab_. I am asking because there is a custom form type _OPD_. If yes, what could be the desirable output?

@tangollama does it make sense to add the lab custom form output here from the business perspective? For instance, adding a `custom-form-manager` right after `<li>` would lead to the following picture:

![bildschirmfoto vom 2018-02-15 15-15-27](https://user-images.githubusercontent.com/9863365/36261564-0cb342f6-1265-11e8-89bf-8ad2560260cb.png)

**Comment by tangollama** [comment]
@stukalin yes. That does seem to make sense. Go for it.

**Comment by KenyanGeek** [comment]
@stukalin sorry for the late response. This seems to be what i envisioned....If so this is great and excellent work......i'll go ahead and test it. But yes it does business sense as some patients come in only for lab tests and hence it would make sense to have them carry their OPD reports from the lab for whatever reason they want.
