### ISSUE TITLE
Update ember and ember-data to the latest versions (goal is at least v2@latest)

### ISSUE THREAD

**Issue by stukalin** [HospitalRun/hospitalrun-frontend#1365]
Let's move our ember and be prepared for the v3, which is in beta now. The latest version is 2.18 at the moment of writing. Whoever picks it please use the [deprecation guide](https://www.emberjs.com/deprecations/) and get rid of all the deprecation messages occured

**Comment by alexanderbrown21** [comment]
Looking at the ember.js deprecation guide which is fairly short, it specifies that propertyDoChange and propertyWillChange will have to be replaced with notifyPropertyChange. When grepping all files in the application it appears that only one file will have to be changed which is vendor-d8042eae6c7c66..js found in /prod/assets. Is this autogenerated code because of how its written? If so, would have to find where it's generated from to see how setting the properties. The other deprecation in the ember guide doesn't appear to affect your application.

**Comment by stukalin** [comment]
@alexanderbrown21 firstly we need to update it to v2@latest. And I believe we'd face a plenty of deprecations on that path. If it'd be possible to make it v3 right afterwards - even better.

`vendor-whatever` is surely an autogenerated code. The application code is in `/app/`. But I'd alse have a look at the `node_modules` which can give you deprecations as well (see #1369) for instance.
