### ISSUE TITLE
Adding New Note in history fails

### ISSUE THREAD

**Issue by drakemedic** [HospitalRun/hospitalrun-frontend#1429]
**Expected behavior:** Adding patient history results in the history being visible and accessible through the patient record.

**Actual behavior:** Adding history fails to update the record. New note is not added to the record.

**Steps to reproduce:** Select a current patient, select history tab and +New Note, type in history, click add, refresh page

**Screenshots (if applicable):**

**OS and Browser:** Linux Mint 18.2,  Firefox 59.0.2

**Comment by drakemedic** [comment]
This may be a misunderstanding on my part about how the history tab should function. The notes are in fact added, but you need to open the event in the history and then look under notes. I interpreted "History" as medical history.

**Comment by MatthewDorner** [comment]
Yeah, but there are some pieces of information that, if present, will be summarized on the History tab with the visit.
![visit summary](https://user-images.githubusercontent.com/36939751/40021337-21174a52-578a-11e8-9822-79fdf91f89bb.png)
Do you think it would be preferable to have the note show along with this information? It seems like it might be, if the Note is important enough to put that "New Note" button right on the History tab.

**Comment by MatthewDorner** [comment]
Looked into this some more, it does save the patient-note record and saves it with Visit B's GUID in the 'visit' field, it just doesn't also update the Visit B record so that its 'patientNotes' field will have the new note's GUID. And that's apparently because the active Visit controller still has Visit A as its model, and the afterUpdate method in patient/notes/controller.js goes to the visit controller and has it update its current model.

I started working on a fix here. https://github.com/HospitalRun/hospitalrun-frontend/compare/master...MatthewDorner:fix-visit-notes
