### ISSUE TITLE
Cannot add Imaging Pricing Types manually

### ISSUE THREAD

**Issue by drakemedic** [HospitalRun/hospitalrun-frontend#1444]
**Expected behavior:** Edit Lookup Lists, select Imaging Pricing types, add pricing type

**Actual behavior:** No option to add a pricing type is available, only file upload.

**Steps to reproduce:** Select Lookup lists from Admin menu, go to Imaging Pricing Types, try to add new pricing type

**Screenshots (if applicable):**
![screenshot from 2018-05-30 01-21-21](https://user-images.githubusercontent.com/26960962/40692144-e85a9fa0-63a7-11e8-918e-c86e1b393cdd.png)

**OS and Browser:** Hospitalrun-server (Ubuntu 16.04) accessed via Linux Mint 18.3 and Firefox 60.0.1

**Comment by stukalin** [comment]
Hmm.. there was an issue #877 and the commit https://github.com/HospitalRun/hospitalrun-frontend/commit/aa09e64951859592804ff541e31dda5b2b058ada fixing that. I don't know any more

**Comment by MatthewDorner** [comment]
yes, it looks like aa90e64 was intended to stop you from deleting default items, but also made it impossible to add items. so I guess we'd need to differentiate between default and non-default items.

Also what browser did you take that screenshot with? Mine has the checkboxes positioned differently different in Chrome and Firefox: 
![imaging_pricing_types](https://user-images.githubusercontent.com/36939751/42910386-fa7ae81c-8aac-11e8-8404-7b60876e69cc.png)

**Comment by MatthewDorner** [comment]
huh, seems more complicated than I thought. should read #1139 as well.

**Comment by drakemedic** [comment]
My screenshot was from Firefox.
I don't know whether the Imaging Pricing Type is actually necessary for the functioning of the system. It was just strange that it was there before and then disappeared - although I can see why that happened now. As long as it's not required for the generation of invoices or correct addition of imaging prices, it doesn't matter. It does mean however, that on the list of prices, there are now gaps in the pricing type column, which is a bit confusing - presumably these gaps won't exist in a fresh install.
![image_pricing_type](https://user-images.githubusercontent.com/26960962/43195977-78ff2134-8ffe-11e8-9d97-09bf646302ab.png)

**Comment by MatthewDorner** [comment]
1) I'm still unclear on what the "Type" does for pricing item types that support it (Ward and Procedure). It some effect beyond purely descriptive, right?

2) There is actually a bug for Imaging and Lab. They're supposed to always get the default "Imaging Procedure" and "Lab Procedure" as their types but in fact they only get assigned that value when categoryChanged action is triggered, meaning if you go directly to the "Imaging Pricing" tab in your screenshot and add one, it will be blank, like your "Chest XRay" item was. This should be easy to fix.

3) Since it sounds like Ward and Procedure pricing types won't be editable, we could remove the lookup lists, although the way it is now won't cause any bugs, so probably not a priority.

**Comment by MatthewDorner** [comment]
from @drakemedic on Slack, regarding the problem here: "For the lab types, they are required to add lab tests to the system. There doesn't seem to be any other way to do it. Now that it is disabled in the lookups, you can't add any lab requests from a fresh install. I have one lab type available - "Full Blood Count". I need a whole bunch of other tests"

**Comment by MatthewDorner** [comment]
Working on this one now: https://github.com/MatthewDorner/hospitalrun-frontend/tree/pricing-types
