### ISSUE TITLE
Inventory quantity count error

### ISSUE THREAD

**Issue by ilhoon** [HospitalRun/hospitalrun-frontend#1537]
**Expected behavior:**
Inventory should decrease if medication is used in procedure.

**Actual behavior:**
There is no change in inventory.

**Steps to reproduce:**
Use medication in any procedure and proceed to checkout.

**Comment by MatthewDorner** [comment]
I noticed this too.

When you make a Medication request from Medication -> Requests, or Visit -> Orders -> New Medication, it creates a Medication record which is linked to the inventory item and when fulfilled, the quantity is removed from inventory.

But when you add Medication to a Procedure, it creates a proc-charge record instead. Proc-charge is used elsewhere for charging Ward and Procedure pricing list items (Visit -> Charges, Procedure -> Charges) and these charges automatically appear on invoice, but for Medication it just refers to a Inventory item with no price. And it doesn't remove the medication from inventory, and it doesn't appear on invoice.

The related issue is that there is no obvious means by which to charge for medication. There is no place to enter pricing for medication.

If you want a workaround for now, you can add the Medication to Visit via Visit -> Orders -> New Medication instead of Procedure.
