### ISSUE TITLE
Changing locale doesn't update all text

### ISSUE THREAD

**Issue by MatthewDorner** [HospitalRun/hospitalrun-frontend#1567]
This issue was observed when testing https://github.com/HospitalRun/hospitalrun-frontend/pull/1553, although it was present before the switch to ember-intl.

Originally reported by @chadian: https://github.com/HospitalRun/hospitalrun-frontend/issues/1561#issuecomment-439645886

Switching the locale updates some of the text fields but not others. Refreshing the browser will ensure all text is in the correct locale. Problem seems to be that switching locale only immediately updates properties that are directly referencing the translation macro, but not properties that are returned from a computed function or otherwise set programmatically.

![locale refresh](https://user-images.githubusercontent.com/36939751/48877008-e371e580-edc6-11e8-9e9e-1cea7552996e.png)

**Comment by jfdnc** [comment]
There appear to be at least two reasons this is happening. 

The first is computed properties only firing once on some of the controllers. For example, in the inventory/reports controller shown in your screenshot, the 'reportColumns' computed property supplies the labels for the checkboxes. That computed property doesn't have any dependent key it is referring to, so it only fires on a page reload. Adding 'intl.locale' as the dependent property will recalculate those on language select and solve that issue. This type of issue appears in several controller files (other than the one shown in screenshot) for various computed properties.

The second has to do with macro.js. The inventory/reports route.js, for example, is using hospitalrun/macro, and that appears to not be getting recomputed on locale change. This issue is also happening in various files.

I'll look more into this and submit a PR in this coming week at some point. Just want to make sure all the relevant files are touched, and that there are some tests for that. Will update.

**Comment by jfdnc** [comment]
Just updating that I'm still working out all the locale change issues. There are several spots in the app where the various intl functionality is accessed in different ways, so I'm making sure to comb through all the various spots. Should have a PR with the relevant changes in the next couple of days.
