### ISSUE TITLE
Unmaintained project?

### ISSUE THREAD

**Issue by baoqchau** [HospitalRun/hospitalrun-frontend#1605]
**Expected behavior:**
Maintainers (@MatthewDorner and @donaldwasserman, I believe so, based on the commit's history) updates the project accordingly.
**Actual behavior:**
No updates to the project since Dec, 2018.
**Steps to reproduce:**
Project's GitHub history.

Hello @maintainers,

I used to contribute to this project a year ago because of its altruistic and meaningful values. However, due to school time, I don't have much time left to continue contributing. Fast-forward today, I am thinking of contributing again because I have some free time now. I tried to contact the maintainers on GitHub but no one replied back to me (I sent it 4 months ago and still no replies yet). Also, I see that the latest commit is on December last year. As a result, I wonder if this project is still being maintained? I know that it's super hard to both work full-time as well as maintain an open source project, so if I can help this project in any way, please let me know.

Thanks a lot for your help for this project so far.

**Comment by MatthewDorner** [comment]
Hello. I was helping maintain for the later half of 2018 but I'm no longer able to. I'm not sure about the disposition of other maintainers, although you are correct it's not been active.

There is a channel on the slack, #public-maintainers on https://hospitalrun-slackin.herokuapp.com/ to discuss maintaining the project. It seems to me the project is at a point where in order to get to the next stage, it may require for the project to get picked up by some organization that provides medical services and can provide more resources (management, testing, etc) than the current individual open source contributors can provide.

**Comment by broerse** [comment]
@baoqchau @MatthewDorner We and other organizations would have invested resources and money a long time ago if the project was not GNU licensed. We considered to do it and decided against it when ember-pouch switched to the [Eventually Consistent](https://github.com/pouchdb-community/ember-pouch#eventually-consistent) relational data. I think therefore that the next stage to save the project is changing the license to MIT, Apache or similar before trying to find organizations that will invest in resources. Don't get me wrong, I love the project.

**Comment by jeremykohn** [comment]
If changing the license to MIT or Apache would help attract investors and move the project forward, it would be great to find an expert in the field who can help with relicensing or dual-licensing.

Anyone know of a copyright lawyer with experience in open source? Maybe someone will do it it pro bono, or it might be worth spending money from the project budget to hire a lawyer given how important this is.

@baoqchau @MatthewDorner @broerse

**Comment by dhavala** [comment]
+ 1 for changing the license to MIT

**Comment by MatthewDorner** [comment]
I don't know much about licensing or what the ramifications will be, so I will mostly defer to others (for whatever say I have, as I'm not sure who has the authority to make such a decision). My point was just that the project seems to now require more support than what it's getting from random interested individuals like myself. A big reason is the type of project this is. It's one thing to develop the project to the point it's at now, another big step to get it from here to a point where people will consider really using it.

We will need to get input on this from the project creators, @jglovier @tangollama @jkleinsc ?

**Comment by MatthewDorner** [comment]
For some additional info, we did a survey last year to see where potential users were at with the software. It revealed a couple cases where people considered using the software or tested it to some extent, but discontinued due to lack of documentation, installation and technical support.

The project needs to be able to offer thorough support to potential users for testing and deployment, which I tried to do to the extent I was able, but I don't have the necessary background in hospital and EMR administration to do this effectively. Also, the feedback that would be gained from such user engagement is needed for the project to determine development priorities. This is why I'm saying the project needs more than additional coding hours, and I'm not sure how that kind of support should be obtained (again, probably because of my personal lack of experience in the area).

**Comment by fox1t** [comment]
Hi @baoqchau, I am excited 🎉 🎉 🎉 🎉 🎉  to inform you that the project is active again. We will publish our Roadmap to the 2.0 version in few days. And speaking of license, it will become MIT ;)

I can anticipate that it will be a React app. Of course we need more active contributors, so just stay tuned :).

**Comment by dhavala** [comment]
welcome and thanks Maksim. That is a great news.

**Comment by cupliz** [comment]
@fox1t if the next version builds with React, I would love to join as a contributor.

**Comment by tehKapa** [comment]
Hi @cupliz. Join our [Slack workspace](https://hospitalrun-slackin.herokuapp.com/), #contributors channel
