### ISSUE TITLE
Successful alert when new related person is added

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#1764]
## Scenario
**AS**

A user with write access to a patient

**I WANT**

A notification that I have successfully added a related person to a patient

**SO THAT**

I am not confused to whether or not the related person has been successfully added.

## Acceptance Criteria
**GIVEN**

Write access to the patient

AND

I have clicked the add new related person button after successfully filing out the new related person form

**WHEN**

The related person is successfully created

**THEN**

I should receive a toast in the top left corner saying I have successfully added the new related person

**Comment by ocBruno** [comment]
Attempting to start this one implementing the toaster component but running into css issues. Not sure if the styles are compiling as they should be or maybe if it's because of an outdated components library but the compiled scss folder is empty in the current components library.

Here is an example of toastify that uses inline styles and also allows options to be passed to the component. Although I think fixing the external styles keeps things decoupled and applying the options parameter would only benefit the toaster. If this component could use an update i'm willing to create and work on that issue before tackling this one!

**Comment by MatthewDorner** [comment]
I see, the toast that appears when adding a new patient is also not the right color. This seems like a separate issue though. This issue only needs to make the toast appear after adding the related person, and we can open a new issue to fix the CSS.

**Comment by jackcmeyer** [comment]
Ageee with @MatthewDorner here. Let’s just get the toaster appearing and we will worry about colors later!

**Comment by ocBruno** [comment]
Hey @jackcmeyer @MatthewDorner 
Tried giving this one a shot but was a little unsure on where and how to handle the async action within redux. The css is styling is practically non existant but I added the main functionality I'm just not sure about the design pattern if anyone has any ideas I tried keeping things decoupled and also added some other organization suggestions.
--
-There's also a suggestion I think is interesting to start thinking about which I have to remove from a comment. It's about abstracting Patient into a Person with types to prepare for other facility members 
-Not sure if the error toast or other modifications needs their own issues or not but if so I can split the modifications and create the issues.

**Comment by oizuldan** [comment]
Can I take this issue?

**Comment by ocBruno** [comment]
> Can I take this issue?

Hey @oizuldan, I've been really busy these past days so feel free!

**Comment by oizuldan** [comment]
@jackcmeyer can you assign me to this task?
