### ISSUE TITLE
Edit patient details

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#1765]
## Scenario
**AS**

A user with write access to patients

**I WANT**

The ability to edit patient details

**SO THAT**

I can have more accurate patient information or change the patient information when needed.

## Acceptance Criteria
**GIVEN**

An existing patient and a user with write access to the patient

**WHEN**

I click the edit button the on patients page

**THEN**

The fields become editable

AND 

a save and cancel button toolbar appear at the bottom of the screen

AND 

when I click the button, then the updated patient details are persisted

AND

I get a success message saying I have successfully updated the patient details.

## Related Issues
HospitalRun/hospitalrun-frontend#1671

**Comment by tehKapa** [comment]
@jackcmeyer #1738 merged

**Comment by MatthewDorner** [comment]
Still working on this. Trying to see if I can just use the `GeneralInformation` form as New/Edit patient instead of having additional form, but getting in trouble with logic around saving and loading the model, Redux state, and state + props for the form.

I found the code for loading Patients is also currently bugged. The `Spinner` in ViewPatient never gets shown because it's checking for `!patient`, but `useSelector` returns an empty object when patient state is empty. But even if we did check for empty object this wouldn't suffice as the `patient` state could already be loaded with an old Patient you were looking at and there's no way to tell the difference.

Also if you view one Patient with all the fields filled in and then go view a Patient where those fields are supposed to be blank, you will still see the values from the first Patient in those fields, but I think this is a separate bug.

**Comment by jackcmeyer** [comment]
I'm digging into why the component is not updating when the new patient gets loaded.

The store is getting updated, but the component is not reflecting those changes.

**Comment by MatthewDorner** [comment]
It must be something to do with empty strings.

**Comment by jackcmeyer** [comment]
@MatthewDorner I'm finding that it is always holding on to old information (except for the title).

**Comment by jackcmeyer** [comment]
After further investigation, 

This seems like an issue with The TextInput and TextField components in the hospitalrun/components library. 

I verified and all of components are getting passed the proper data, however, `TextInput` and `TextField` are just not displaying them properly. 

I verified this by swapping out `TextInput` and `TextField` with just a normal input field and in `TextFieldWithLabelFormGroup` and `TextInputWithLabelFormGroup` and the screen worked as expected.

**Comment by fox1t** [comment]
> It must be something to do with empty strings.

I really want to avoid passing empty strings for "signaling" that is a new patient. Do you have any alternative ideas, @MatthewDorner ?


> After further investigation,
> 
> This seems like an issue with The TextInput and TextField components in the hospitalrun/components library.
> 
> I verified and all of components are getting passed the proper data, however, `TextInput` and `TextField` are just not displaying them properly.
> 
> I verified this by swapping out `TextInput` and `TextField` with just a normal input field and in `TextFieldWithLabelFormGroup` and `TextInputWithLabelFormGroup` and the screen worked as expected.
> 
> I've opened an issue here to track the work: [HospitalRun/components#259](https://github.com/HospitalRun/components/issues/259)

Good findings @jackcmeyer!

**Comment by MatthewDorner** [comment]
I've written a draft that I think will work. It uses `GeneralInformation` as the form for New, Edit, and View Patient, and `NewPatient`, `EditPatient`, `ViewPatient` containers that manage fetching and saving data and which contain the state.

https://github.com/MatthewDorner/hospitalrun-frontend/compare/MatthewDorner:master...MatthewDorner:edit-patient-draft-3

I have to fix all the tests now, so while I do that, any comments or suggestions are welcome.

**Comment by fox1t** [comment]
If you want, feel free to open a PR so we can discuss it there.
