### ISSUE TITLE
Add autocomplete for dropdowns.

### ISSUE THREAD

**Issue by bhagyas** [HospitalRun/hospitalrun-frontend#211]
Probably use select2 whenever possible.

**Comment by jkleinsc** [comment]
HospitalRun tackles this by using typeahead fields instead of dropdowns where applicable.  These typeahead fields also support the ability for users to add new values.  An administrator can choose to turn off the ability for users to add new values for typeaheads.  In my opinion this gives us greater flexibility out of the box and also means that when a new site comes up an admin doesn't have to spend time creating values for drop down lists.

HospitalRun does have some spots where dropdowns are specifically used, but in most of those cases, the dropdowns are small data sets, so I'm not sure that autocomplete is needed for them.

**Comment by tangollama** [comment]
@bhagyas, unless you have additional questions / concerns / input, I'm inclined to close this issue. Let me know if @jkleinsc response is sufficient.

**Comment by bhagyas** [comment]
Apologies for the delay in response. 

Having select2 or similar would enable picking up values that don't start from a particular sequence of characters.
