### ISSUE TITLE
Ability to view a diagnosis

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#2129]
## 🚀 Feature Proposal

Currently, the list of diagnosis are not clickable. This issue is to make them clickable and create a component that allows a user to view the diagnoses. 

## Technical notes
* the routing should work similar to how care plan routes work

**Comment by dopt** [comment]
Hi, @jackcmeyer I would like to try this issue.

I have a question though, it seems that the diagnoses has only 2 fields which are diagnosis name and date, as compared to care plans which has much more existing fields, do you think the "View" button is necessarily in this case? Since we could be showing the 2 fields in the table row by default.

**Comment by blestab** [comment]
Hi @dopt 
Additional fields are being added to diagnosis via #2128 hence the need for this ability, I think.

**Comment by reidmeyer** [comment]
Yup, I'm working on #2128, so I can tackle this once I'm done there since this is directly related.

**Comment by jackcmeyer** [comment]
> Hi, @jackcmeyer I would like to try this issue.
> 
> I have a question though, it seems that the diagnoses has only 2 fields which are diagnosis name and date, as compared to care plans which has much more existing fields, do you think the "View" button is necessarily in this case? Since we could be showing the 2 fields in the table row by default.

@blestab answered the question perfectly. Also, there will eventually be some sort of workflow for a diagnosis which will need the ability to view a diagnosis.

**Comment by dopt** [comment]
@blestab @jackcmeyer Got it, thanks. 
It's better to wait for #2128 to be finished first since both issues are linked.
> Also, there will eventually be some sort of workflow for a diagnosis which will need the ability to view a diagnosis. 

For now, I will probably reuse care plans' workflow for diagnoses, do let me know if there's different opinion on the matter.

@reidmeyer I can take care of this issue once #2128 is done, don't worry about that.

**Comment by reidmeyer** [comment]
@dopt #2128 is done. Just wanted to update you in case you wanted to get reassigned to this issue.

**Comment by danikyl** [comment]
Hi guys, I'd like to handle this one!

**Comment by jackcmeyer** [comment]
> Hi guys, I'd like to handle this one!

Go for it @danikyl!

**Comment by morrme** [comment]
Hi @danikyl ! What is the current status of your work on this issue? Can we help in any way?

**Comment by danikyl** [comment]
> Hi @danikyl ! What is the current status of your work on this issue? Can we help in any way?

Hello there! Sorry for the delay. I need 5 more days to complete this work.

**Comment by fox1t** [comment]
> > Hi @danikyl ! What is the current status of your work on this issue? Can we help in any way?
> 
> Hello there! Sorry for the delay. I need 5 more days to complete this work.

No worries! And thanks for looking into this! :)

**Comment by anthonyaperez** [comment]
Hi @jackcmeyer @fox1t @tehKapa, I would love to take this issue on if it's still open.

**Comment by jackcmeyer** [comment]
> Hi @jackcmeyer @fox1t @tehKapa, I would love to take this issue on if it's still open.

Go for it!
