### ISSUE TITLE
Display additional patient info when searching patients to add as Related Person

### ISSUE THREAD

**Issue by JDarke** [HospitalRun/hospitalrun-frontend#2132]
## 🚀 Feature Proposal

When searching for a match by name in the Add Related Person dialog, it should display additional identifying information (such as zip code) alongside the name of each listed match.

## Motivation

When searching for a match in existing patients, it only searches by name, and doesn't display any other info to the user before they confirm the match as a related person.

This seems likely to cause issues if say, the user is searching for a person with a fairly common name, and they are returned as a match when in fact the user is looking for someone completely different who is not yet on the system.  Similarly, when presented with three matching names and no way to tell them apart, the user either has to guess, or exit the dialog and navigate away from the current page to look them up individually.

![Screen Shot 2020-06-16 at 18 16 17](https://user-images.githubusercontent.com/52716187/84806441-99320400-affd-11ea-8ad0-daf3603ff5db.png)

## Example

The search bar in the Add Related Person dialog should also display part of the address, for example, for each match so that the user can at least distinguish between multiple matches with the same name, and can tell straightaway if the match is someone in a different city when it's a person from the same household that they're looking for.

If Dr Smith is searching for Jane Doe to add as John Doe's partner, they can select the correct Jane Doe with the additional matching info.

Suggested solution is to display Name, Age, Sex, then the first line of the address (truncated to a set max length) and zip code:  

> Jane Doe - 32 - F - 10a High Street - AA12345

**Comment by nischayv** [comment]
Can I work on this feature?

**Comment by tehKapa** [comment]
@JDarke did you just report the feature or were you also planning to develop it?

**Comment by JDarke** [comment]
I'm happy for you to take this one, @nischayv .  

Any redesign of the layout of the dialog box could be affected by #2106 at some point, as we might be moving the dialog box fields onto the main page...but that's not an issue if you're just going to change the text displayed in the search dropdown, as that functionality will be carried over unchanged.

**Comment by nischayv** [comment]
Do we still want to retain the patient code in the text? If we choose to retain that we should ideally skip the address otherwise the text will become too long (we would have to truncate most of the address and it wouldn't make sense to have it at that point). What does the patient code signify? If it is some sort of unique identifier I think it makes sense to retain it. Also, if we do choose to display the address, do we arbitrarily display the first one the user entered while creating a new patient? Since it doesn't look like we have any concept of primary address, secondary address, etc and if the user entered it in the incorrect order, the address may not necessarily serve as a unique way to identify an individual as the person adding the related person may not be aware of the other address. 

Also, if the sex of the person is `Other`, as mentioned in the example would `O` be sufficient to understand what the letter signifies? Might make sense to display the full text for sex - `Male`, `Female`, `Other`.

@JDarke @jackcmeyer thoughts?

**Comment by jackcmeyer** [comment]
@nischayv Hmmm.... maybe a better option would be to display date of birth. It is, possible, but unlikely that someone with the same name and DOB would exist.

**Comment by nischayv** [comment]
Even though unlikely, in the off chance that it does happen, it would be impossible to pick the correct patient with just the name and DOB. If the patient code is a unique identifier, I believe it would be reasonable to have the DOB and code. Something like this - `John Doe - 1990-12-10 (P-WYLx1mc1_)`.

**Comment by jackcmeyer** [comment]
@nischayv let's do that.
