### ISSUE TITLE
Display success toast after creating a lab

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#2170]
## Scenario
**AS**
A user who is able to create a lab

**I WANT**
A success message displayed after I create the lab

**SO THAT**
I know that the lab was successfully created

## Acceptance Criteria
**GIVEN**
A lab is being created

**WHEN**
It is successfully created

**THEN**
It should display a toast message saying `${lab.type} for ${lab.patient.name} successfully requested.`

## Related Issues
HospitalRun/hospitalrun#269

**Comment by anyapawar** [comment]
Hi! Can I take this? (With the WashU Team)

**Comment by jackcmeyer** [comment]
@anyapawar I have assigned this to you!

**Comment by yosephAHMED** [comment]
To whom it may concern,

Has there been any progress on this issue?

Best,
Yoseph

**Comment by anyapawar** [comment]
#2277 @jackcmeyer This PR adds a success toast when a lab is created (NewLabRequest.tsx line 67-78)- however, patient ID is being displayed instead of patient full name. We just wanted to link the PR to this issue because it solves most of the concerns, but we don't think we will be able to figure out how to display the patient's full name. Maybe this issue can be updated for someone else to claim ( @yosephAHMED ). Thanks!

**Comment by jackcmeyer** [comment]
See #2293
