### ISSUE TITLE
Align quick create menu items order with sidebar items order

### ISSUE THREAD

**Issue by blestab** [HospitalRun/hospitalrun-frontend#2326]
## 🐛 Bug Report

The order of quick create menu items needs to align with the sidebar menu items order. 

NOTE: This is a followup to #2305 

![image](https://user-images.githubusercontent.com/5468546/90959939-50d01000-e49e-11ea-9c79-7b59933d2593.png)

## To Reproduce

Open the quick create menu and notice the ordering of menu items is different to how they are ordered in the sidebar.

src/shared/components/navbar/Navbar.tsx
```js
  // For Desktop, add shortcuts menu
  const addPages = [
    pageMap.newPatient,
    pageMap.newAppointment,
    pageMap.newLab,
    pageMap.newMedication,
    pageMap.newIncident,
    pageMap.newImaging,
  ]
```

## Expected behavior

The order of the menu items on the quick create menu should be the same as the ordering of the sidebar menu items

![image](https://user-images.githubusercontent.com/5468546/90960022-fc796000-e49e-11ea-858a-4b647e88be55.png)

src/shared/components/navbar/Navbar.tsx

```js
 // For Desktop, add shortcuts menu
  const addPages = [
    pageMap.newPatient,
    pageMap.newAppointment,
    pageMap.newMedication,
    pageMap.newLab,
    pageMap.newImaging,
    pageMap.newIncident,
  ]
```

## Your Environment

- *node version*: 6,8,10
- *fastify version*: >=1.0.0
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by alti21** [comment]
Can I take this?

**Comment by blestab** [comment]
Sure @alti21, go for it!

**Comment by michaelkramer** [comment]
I did the changes just to see how the system works.  This is very goood!!  
I like the rules on commits I feel like some documentation would be nice.  

I know this was assigned to @alti21 

@blestab

**Comment by morrme** [comment]
@michaelkramer were you working with @alti21 ?

**Comment by michaelkramer** [comment]
> @michaelkramer were you working with @alti21 ?

No I'm not working with them. I'm just a software engineer looking to help out and see how other projects are built.

**Comment by morrme** [comment]
> > @michaelkramer were you working with @alti21 ?
> 
> No I'm not working with them. I'm just a software engineer looking to help out and see how other projects are built.

@michaelkramer 


There is typically a `CONTRIBUTING.MD` file that explains the rules and guidelines for contributing to any open source project. There is also an Issues list for most projects that details the issues currently in need by a project, and tags are left on each issue such as `help wanted` to indicate that a potential contributor's support is needed.  There are several issues that have not been assigned to anyone. If you wished to "help" with a task that was previously assigned to someone else, it would have been better to ask for permission in advance, or to select an issue that may have been assigned over a week or two ago, ,instead of something assigned 2 days ago. This is so that the work of the person who has committed their time and efforts to support the project is not in vain. 

Finally, if you only wished to do the changes to see how the project works, you could have tested it on your branch without submitting a pull request. Please let us know if you need more instructions on how Github branches work, or how to deploy a project locally.

**Comment by alti21** [comment]
@blestab I'm having an issue, I cannot login into Hospitalrun after setting it up on my computer. Nothing happens when I click sign in

**Comment by blestab** [comment]
Hi @alti21 im offline now but why do you hop on over to our slack there might be others still online who might be able to help you out. You can join our slack via this link https://hospitalrun-slack.herokuapp.com/

**Comment by mani9896** [comment]
Hey there, i am a newbie and want to start contributing can i give a try here?

**Comment by blestab** [comment]
Thank you for offering @mani9896 this one is already assigned to someone else. Stick around we should be able to find you something easy to do. In the meantimg checkout our how to contribute guide here https://github.com/HospitalRun/hospitalrun-frontend/blob/master/.github/CONTRIBUTING.md and also be sure to join our slack here: https://hospitalrun-slack.herokuapp.com/
