### ISSUE TITLE
Move title functionality to a `TitleProvider` rather than redux

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#2354]
## 🚀 Feature Proposal
The title functionality should move to use the react context API using the "provider" pattern that can be seen here: https://kentcdodds.com/blog/how-to-use-react-context-effectively

The `useTitle` hook should remain unchanged

## Motivation
- Remove redux

**Comment by WinstonPoh** [comment]
Hello, I came across this warning when on working on another issue refactoring scheduling. It is caused by the useUpdateTitle I think, and appears for basically all the pages. Just thought I'd check with some one here.

![Selection_015](https://user-images.githubusercontent.com/7601526/94501752-1442c180-025f-11eb-9b85-9b4605aa7828.png)
![Selection_016](https://user-images.githubusercontent.com/7601526/94501756-16a51b80-025f-11eb-86d8-bc4a2a18c798.png)

I had to put the useUpdateTitle call into useEffect to rid of the error, because it cannot render the title while rendering the component. Thoughts?
