### ISSUE TITLE
Allow External Results Submission

### ISSUE THREAD

**Issue by bkerensa** [HospitalRun/hospitalrun-frontend#249]
If we wanted to add support for HospitalRun in Glucosio we would need some sort of API with the ability to send health data directly into a Hospital Run instance. Is this possible currently? The kind of data we would like to share is Blood Glucose Levels, HBA1C and Weight.

**Comment by jkleinsc** [comment]
@bkerensa we currently don't have an API that does that, but it sounds like a candidate for the [HospitalRun server](https://github.com/HospitalRun/hospitalrun-server) project.  Feel free to log an issue there.

**Comment by enyachoke** [comment]
:+1: .
I think this makes a lot of since in Countries like Kenya where most hospitals don't have lab and imaging or their facilities are ill equipped meaning patients have to be sent to external facilities for labs and imaging before coming back to the hospital. The same may also apply for the pharmacy.

**Comment by tangollama** [comment]
Closing in favor of https://github.com/HospitalRun/hospitalrun-server/issues/11
