### ISSUE TITLE
Search Views Inconsistency

### ISSUE THREAD

**Issue by blestab** [HospitalRun/hospitalrun-frontend#2503]
## 🐛 Bug Report

> While fixing the spelling of 'canceled' for the usEn locale, I noticed that the ViewMedicines component has a much smaller width for the medicines table.

We need to make the Search views for patients, medications, labs, imaging, and incidents consistent.

## To Reproduce

Access the list of medication requests and note the width inconsistency. 

## Expected behavior

UI should be consistent.
- The search box and other filter fields should ALL use class form-control not form-control-lg
- The search filters and table of search matches must all be aligned with the breadcrumbs section. 
   Suggestion: Try wrapping them in a container with classes _container px-0_, Medications might already have this wrapper and may only just need the px-0 class added

## Your Environment

- *node version*: 6,8,10
- *fastify version*: >=1.0.0
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by blestab** [comment]
@FanciestW here is the new task. May you sign the CLA for your other PR.

**Comment by FanciestW** [comment]
@blestab CLA has been signed for the other PR. I would like to work on this issue, may I be assigned to this issue? Thank you very much!

**Comment by blestab** [comment]
> @blestab CLA has been signed for the other PR. I would like to work on this issue, may I be assigned to this issue? Thank you very much!

Awesome! thanks 
I have added this onto your name.

**Comment by FanciestW** [comment]
@blestab Do you think the title and objective of this issue can be changed to make the Search views for medications, labs, imagings, and incidents consistent. A potential new title might be "Search Views: Make Consistent". I used the Patients' research view as a guide and changed the JSX for each Search view component to all use Container, Row, and Column from `@hospitalrun/components`. Here are some before and after screenshots.

I also noticed that the width inconsistency are worse on larger screens instead of smaller screens. (Laptop screen vs. Monitor)

Before:
![LabsSearchView_Before](https://user-images.githubusercontent.com/9480166/101440320-76b1e100-38e4-11eb-99aa-1393b36baa7c.png)

![MedicationsSearchView_Before](https://user-images.githubusercontent.com/9480166/101440267-5e41c680-38e4-11eb-8a13-1cfae4f6dae3.png)

After:
![LabsSearchView_After](https://user-images.githubusercontent.com/9480166/101440336-7c0f2b80-38e4-11eb-970b-3ff7ba5e6a28.png)

![MedicationsSearchView_After](https://user-images.githubusercontent.com/9480166/101440272-639f1100-38e4-11eb-92ca-76a1164642f6.png)

**Comment by blestab** [comment]
Thanks @FanciestW I have updated the title and description so you can look at making all view consistent, including the patients view as well
