### ISSUE TITLE
server duplication

### ISSUE THREAD

**Issue by pgte** [HospitalRun/hospitalrun-frontend#264]
When working on https://github.com/HospitalRun/hospitalrun-server/issues/5 I noticed that there is a duplication of the server code: what it seams to be a trimmed-down developer version of the server sitting [here](https://github.com/HospitalRun/hospitalrun-frontend/tree/master/server) and this repo.

I think it would be good to deduplicate so that we can easily introduce changes without needing to sync / simplify on the front-end repo.

Before I propose something, I'd like to know if you have thought about this. If not, I can propose something to solve this.

**Comment by jkleinsc** [comment]
@pgte if I recall correctly I think the code in HospitalRun/hospitalrun-server was created first and then some of it was ported over to  HospitalRun/hospitalrun-frontend so that you could run the ember frontend in development without setting up the server.   HospitalRun/hospitalrun-server has more features than  HospitalRun/hospitalrun-frontend, but I think it would be great to somehow combine them with submodules or something like that.  I haven't given much thought since I haven't had time to tackle it, but if you have a solution for this, I would like to hear about it.

**Comment by jkleinsc** [comment]
This issue was resolved with a90d132a04d27a7dfd3339bda857d02117f015ef
