### ISSUE TITLE
More than two genders

### ISSUE THREAD

**Issue by forteller** [HospitalRun/hospitalrun-frontend#301]
Sorry if this is the wrong place for this.

When registering a patient in HR you have to choose between male or female gender. But that is a false dichotomy. https://en.wikipedia.org/wiki/Gender

Facebook has added lots of different genders to choose from, but at the very least you should add a third "other" category.

Thanks for your amazing work!

**Comment by tangollama** [comment]
Thanks for bringing this up. Nomenclature matters, and on this one, we made an honest mistake. The field is [mislabeled](http://emedicine.medscape.com/article/917990-overview) gender; it should be tracking sex, since that's what we're concerned with medically. 

Additionally, we need to make the system more flexible and (to your point) not make the field binary. We're going to adjust that using the system's configurable list construct.

**Comment by jkleinsc** [comment]
@tangollama Agreed.  I am going to change the label to "Sex" instead of "Gender" and I am going to change the field to use a lookup list/typeahead so that new values can be added by users.

**Comment by hex007** [comment]
Even if sex is tracked there will be exceptions

https://en.wikipedia.org/wiki/True_hermaphroditism
http://www.isna.org/faq/conditions/ovo-testes

Letting users add new values seems like a good idea
