### ISSUE TITLE
Cashier screen

### ISSUE THREAD

**Issue by tangollama** [HospitalRun/hospitalrun-frontend#303]
See functional needs here. https://github.com/HospitalRun/hospitalrun-frontend/wiki/Requirements:-Cashier-Role

**Comment by marcorosas1991** [comment]
I can take this issue @tangollama

**Comment by karunkannan** [comment]
Does this still need to be completed?

**Comment by baoqchau** [comment]
Hello @jkleinsc. I would like to work on this. You know which file I need to change so that when I log in with a specific role, the left navigation bar will display only the capabilities of that specific role? I tried to add "Cashier" role in both `mixins/user-roles.js` and `mixins/user-session.js` but looks like it's not working. Thanks a lot.

**Comment by jkleinsc** [comment]
@baoqchau you are correct that you would need to add the role to both `mixins/user-roles.js` and `mixins/user-session.js`.  Security in HospitalRun is based on the concept of roles and capabilities.  `mixins/user-roles.js` defines the available roles in the system and `mixins/user-session.js` defines the capabilities for each of those roles.  So if you add a new new in `mixins/user-roles.js` you then would need to go into `mixins/user-session.js` and add the new role name to the the capabilities listed under defaultCapabilities (for example for a cashier to have access to the billing menu, they would need the `billing` capability).  As far as navigation is concerned, `mixins/navigation.js` defines the navigation and which capability is required to show that navigation item, so you can look there to determine what capabilities are needed to show the desired navigation items.  

Does that make sense?

**Comment by jkleinsc** [comment]
@baoqchau I marked this item as in progress, so it is yours to work on.  Please let me know if you don't end up working on this.

**Comment by baoqchau** [comment]
Thanks @jkleinsc. I will update status as I am working on this.

**Comment by baoqchau** [comment]
@jkleinsc should i create a new `cashier` route that will have cashier screen and additional functionalities, like `Add Payment`?

**Comment by jkleinsc** [comment]
@baoqchau, yes this feature request will require creating a new route and navigation item.

**Comment by baoqchau** [comment]
Hi @jkleinsc, can u reopen this issue? I still have the `Cashier Screen` and `Receiving payments not related to billed invoice` incomplete. I just want to divide the requirements from here [https://github.com/HospitalRun/hospitalrun-frontend/wiki/Requirements:-Cashier-Role](url) into small PR so that it is easier to manage. Thanks.

**Comment by jkleinsc** [comment]
@baoqchau done.
