### ISSUE TITLE
Button not visible properly

### ISSUE THREAD

**Issue by csawai** [HospitalRun/hospitalrun-frontend#313]
When logged in to the application as an admin and while creating a new appointment, it is confusing to understand the add button. The visibility is poor due to color selection.

I am viewing this in chrome on mac. The button color is greenish.
![screen shot 2016-02-17 at 11 13 43 pm](https://cloud.githubusercontent.com/assets/3336524/13118825/15fcb3f6-d5cc-11e5-8524-a0cf8b8497d1.png)

**Comment by jkleinsc** [comment]
@csawai the button is that way because it is disabled until all of the required fields have been filled in. Once all the required fields are filled in the button changes color:
![screen shot 2016-02-17 at 1 17 33 pm](https://cloud.githubusercontent.com/assets/609052/13119792/dffbbd2c-d578-11e5-8ca0-0c1d7a8f07fc.png)

**Comment by jglovier** [comment]
Def agree that it's crappy as is, though. It's awaiting some long overdue design cleanup. I've been meaning to give those buttons a better disabled style, like some type of gray or something. :+1:

**Comment by jglovier** [comment]
Partly addressed in #355.

**Comment by Anisha1234** [comment]
As @jkleinsc said the color on the buttons after filling up the appointment forms is confusing.I am going to  change the disabled,active and hover buttons color states to a more understandable manner . Please review my pull request #971
