### ISSUE TITLE
a Feature request for a currency selector for the system

### ISSUE THREAD

**Issue by csawai** [HospitalRun/hospitalrun-frontend#314]
How about having a countrywise/ currency selector. So when the billing is done, values are just not numbers. Example - $ 10.90 

May be I have missed something in the documentation/wiki

When I look at the Billing feature, It seems that it just shows the number.

Showing currency has lot of advantages :) 
## TODO
- [ ] Ability to specify app wide currency
- [ ] Ability to present formatted currency

**Comment by tangollama** [comment]
Thanks for the issue @csawai. At present, the billing piece is intentionally vague b/c the real issue is handling currency. We didn't want to assume USD, but - currently - we have a constraint of handling only one currency in the system.

I'm going to turn this issue into a request to include a currency configuration (one currency for the whole site) into the admin screen for Billing. However that value is set will determine the DISPLAY ONLY of currency throughout the system.

**Comment by fox1t** [comment]
This is an absolute must have for the 2.0.0 release!

**Comment by rahulinvictus** [comment]
Has this been rolled yet? If not, is there a way to manage this by changing source code?
