### ISSUE TITLE
Create a call to hospitalrun-server for an HL7-based integration with a PACS solution

### ISSUE THREAD

**Issue by tangollama** [HospitalRun/hospitalrun-frontend#342]
Creating an imaging request should inform hospitalrun-server to contact a PACS solution to initiate an imaging request.

For starters the configuration of a server capable of processing HL7 calls / requests could be a configuration in the hospitalrun-server implementation. Long-term we need an administrative screen to capture this and make it editable / configurable later.

**Comment by jupiter** [comment]
We probably need to run an HL7 server alongside/within the hospitalrun-server.

It would make sense to create modules, for HL7 server and client, containing all the necessary abstractions, that we can interface with from the hospitalrun-server.

The components and structure would be something like:

- hospitalrun-server
  - hospitalrun-routes module
  - hospitalrun-dblisteners module
    - *new* listeners for each request that should be initiated
      - *new* hospitalrun-hl7-client module
        - methods for constructing and sending outgoing messages
  - *new* hospitalrun-hl7-server module
    - handlers for incoming messages

Configuration should be passed down from the hospitalrun-server config as a start.

I think that we can implement https://github.com/hitgeek/simple-hl7 for use within the hospitalrun-hl7-client and hospitalrun-hl7-server modules. See https://github.com/hitgeek/simple-hl7/tree/master/examples. This module supports TCP and File transports in raw HL7 format. 

Some PACS services may want to use XML, but we don't know how important it would be to support this. It would be good to have a specific PACS service to develop against in order to gather additional requirements for the implementation of specific message flows.
