### ISSUE TITLE
Cascading delete for patient record

### ISSUE THREAD

**Issue by tangollama** [HospitalRun/hospitalrun-frontend#380]
When deleting a patient, we need to delete all visits, invoices, etc.

**Comment by aboma** [comment]
I am working on this.

**Comment by tangollama** [comment]
Thanks @aboma. @jkleinsc you'll want to pay close attention to this issue to assist and look for the PR.

**Comment by aboma** [comment]
I have written code to delete all of a patient's visits and models related to visits. However, I am having trouble getting a list of invoices for the patient being deleted so that I can delete them. If someone could provide a snippet of how to search the store for invoices for a patient that would help me finish this.  The various ways I have tried to implemented this have all turned up zero invoices even though I have entered one for the patient. My current attempt is the following:

```
   var maxValue = this.get('maxValue');
   var patientId = patient.get('id');
   return this.store.query('invoice', {
        options: {
          startkey: ['patientId', patientId, 'invoice_'],
          endkey: ['patientId', patientId, maxValue]
        },
        mapReduce: 'invoice_by_status'
      });
```

Thank you @tangollama

**Comment by jkleinsc** [comment]
@aboma in order to find invoices by patient, a new view needs to be added to the pouch/couch views by defining it in app/utils/pouch-views.js before the 'invoice_by_status' view:
```javascript
}, {
  name: 'invoice_by_patient',
  function: generateView('invoice',
    'emit(doc.data.patient);'
  ),
  version: 1
}.....
```
Then to find:
```javascript
var patientId = patient.get('id');
return this.store.query('invoice', {
  options: {
    key: patientId
  },
  mapReduce: 'invoice_by_patient'
});
```

**Comment by tangollama** [comment]
@jkleinsc @aboma thinking this still outstanding, yes?

**Comment by jkleinsc** [comment]
@tangollama yes this is still outstanding.
