### ISSUE TITLE
Billed Invoices - Buttons disappear from the invoice

### ISSUE THREAD

**Issue by mnorbeck** [HospitalRun/hospitalrun-frontend#467]
**Expected behavior:**
Buttons to add payment, edit, delete  are always there.

**Actual behavior:**
If you click on add payment, the buttons disappear.   

**Steps to reproduce:**
on beta site
Billing > Invoices > click on the add payment button for an invoice.   The buttons disappear when the dialog comes up.   If you dismiss the dialog with cancel, the buttons are gone.

**Screenshots (if applicable):**

![screen shot 2016-05-13 at 4 21 58 pm](https://cloud.githubusercontent.com/assets/6825179/15260806/ec05a97e-1926-11e6-8285-5a13b9c7e1d5.png)

**OS and Browser:**
OSX   Chrome

**Comment by BrianHC** [comment]
I'll take a look at this issue if nobody else has taken it already.

**Comment by tangollama** [comment]
Marking in progress @BrianHC

**Comment by tangollama** [comment]
@BrianHC any update on this?

**Comment by kaungst** [comment]
I have found fixed the problem and am putting together a pull request.

**Comment by kaungst** [comment]
See https://github.com/HospitalRun/hospitalrun-frontend/pull/538 for the fix

@tangollama

**Comment by gnowoel** [comment]
This problem should only happen when an invoice's total cost is zero.

When clicking "Add Payment", a new payment object would be created and then recalculating of the balance would be triggered. Since the initial value of the `amount` field for the newly created object is zero, we've already paid up for the zero-cost invoice at the moment of clicking the button. The buttons disappear because they are only showing for the unpaid invoices.

Considering zero-cost invoices should be rare in real cases, so this bug should be relatively harmless. Anyway, I've tried to fix it in the following pull request. The idea is simple, I just count for the saved (not new) payment objects when calculating the balance.

I'm totally new to Ember, so please correct me if I'm outright wrong.
