### ISSUE TITLE
Make the Save (Add, Update) buttons always visible

### ISSUE THREAD

**Issue by mnorbeck** [HospitalRun/hospitalrun-frontend#569]
The request is that any button to Save (Add or Update) would always be visible. Users would not need to scroll to the bottom of a page to find the button.    This could mean placing a second copy of the button at the top of the screen.   Request is to make this a standard across Hospital Run

**Comment by jkleinsc** [comment]
@jglovier what do you think about this idea?  Any thoughts on how we might accomplish this - eg floating button as you scroll, or just a button at the top?

**Comment by ShadabQ** [comment]
we can push the button near the header,once the user clicks for edit/save.

**Comment by jkleinsc** [comment]
@ShadabQ I'm not sure I follow what you are suggesting.  Can you explain further what you mean?

**Comment by ShadabQ** [comment]
@jkleinsc i am suggesting something like this

![screenshot from 2016-07-28 04 14 36](https://cloud.githubusercontent.com/assets/5912349/17195269/7c6b9d1e-547a-11e6-956c-11955bc83cc5.png)

**Comment by ShadabQ** [comment]
@jkleinsc :i am suggesting something like this

![screenshot from 2016-07-28 04 20 23](https://cloud.githubusercontent.com/assets/5912349/17195358/d98ceeee-547a-11e6-9536-2c7d40a27e34.png)

**Comment by jglovier** [comment]
@ShadabQ I like where you are heading with that concept. I think we could rethink the screen header a bit (as is that would mean three equal weight buttons which are not all grouped together), but the idea of solving this problem by putting the button in that header area could work.

Honestly, I don't think we need the `new patient` button in that region anyway. If anything, the action there should probably be `view all` or something that takes you back to the patient index. Or, the save button could just be the primary header call to action.

**Comment by mnorbeck** [comment]
Agree with @jglovier  New patient is not needed.  Really do not think you are going to edit a patient, then move to adding new patients, from a workflow perspective.

**Comment by ShadabQ** [comment]
@jglovier @mnorbeck I agree,seems logical.Additionally we do have a new patient on left hand menu.

**Comment by kartik95** [comment]
Is anybody taking up this issue? If not, I would like to take up this issue. @tangollama

**Comment by jscottchapman** [comment]
@kartik95  It looks like you are working on this one.  Is that right?  Just wanted to make sure two people aren't working on the same issue unknowingly.

**Comment by kartik95** [comment]
So, what I get is that we need to have add or update buttons always on the top and 'new user' button not required while editing or creating a user. Right? @ShadabQ @jglovier

**Comment by ShadabQ** [comment]
@kartik95  you may find the suggestions over here 
https://github.com/HospitalRun/hospitalrun-frontend/pull/656

**Comment by mdarmani** [comment]
@kartik95 were you able to complete this one?

**Comment by jkleinsc** [comment]
There have been a couple PRs against this issue and I've come to the realization that this issue really needs some better requirements and/or architectural design before work is started on it.  I am pulling off the help wanted/hacktoberfest labels off of this issue until we can sort out architecturally/UX/requirements wise what we want to do.  Please don't work on this issue until this has been clarified

The main problem is that the location @jglovier has suggested to place the buttons is controlled by the "section" template, but placing buttons in there really messes up firing actions on those buttons because hierarchically speaking the section is at a higher level than the edit screen, so you need someway to push the action down to the controller.

Ideally what should happen is the "section"/module idea needs to be refactored into components so that we can properly handle actions. Also, the title/button bar probably belongs in the edit-panel/item-listing components as opposed to the section which would make this problem easier to solve.

**Comment by Marinlemaignan** [comment]
If i may.
I would suggest having that/those button/s at the bottom right end of the page.
And why not visible if the page doesn't scroll (is smaller than the screen's size).
If the page is longer than screen size, the button is style visible on ready, but hides when you start scrolling down. Shows back up when you scroll back up.
This way you can have as many buttons as you may, and are not obtrusive.
Also if the showing/hiding of those buttons is slightly but visibly animated in some nice googley material style.
Plus if the app is somehow used packaged in a touch-screen device, this makes those buttons instantly accessible to a thumb, while still easy to reach for cursor navigating users.
