### ISSUE TITLE
Search is not working off-line

### ISSUE THREAD

**Issue by mnorbeck** [HospitalRun/hospitalrun-frontend#631]
**Expected behavior:**
Search should work off-line

**Actual behavior:**
Search is not working, the search working dialog comes up, but it never closes

**Steps to reproduce:**
1. login to hospital run
2. wait for sync (watch network activity in dev tools)
3. close tab in browser
4. go off the network
5. open new tab
6. go to hospital run url
7. attempt a patient search

**Screenshots (if applicable):**

n/a

**OS and Browser:**

OSX Yosemite   Chrome 52.0.2743.116 (64-bit)

**Comment by halatef** [comment]
Dear, i am sorry for posting here about this but i don't know wher can i post my squestions

but i need to know how can i get a user manual/documentation for hospital run?

**Comment by dinhvle** [comment]
Anybody working on this issue? I do have a suggestion regarding search, it's kinda hard to tell what you are searching for. It would be better if the search bar is move from the side bar to the main view pages.

**Comment by broerse** [comment]
@dinhvle I am not working on this but we could now use `pouchdb-find`
https://github.com/HospitalRun/hospitalrun-frontend/blob/master/bower.json#L19

**Comment by wolfieorama** [comment]
@dinhvle I have just started on it, I like both suggestions

**Comment by wolfieorama** [comment]
@mnorbeck does this apply for all the records, offline created records, or the synced record only ? I a asking because I am not able to exactly reproduce

**Comment by jkleinsc** [comment]
@wolfieorama the issue is that currently the app tries to call /search/hrdb/ which cannot be reached while offline.  The bulk of the offline support is currently contained in our serviceworker code at /app/serviceworkers/pouchdb-sync.  The solution would be to add an intercept in /app/serviceworkers/pouchdb-sync for the server route /search/hrdb/ that tries to make the call server side and if that fails, it should either perform a "slow search" via a temp view like we do here: https://github.com/HospitalRun/hospitalrun-server-routes/blob/master/routes/20-searchproxy.js or use pouchdb-find as @broerse mentioned.  In order to use pouchdb-find, the proper indexes would need to be built.

This issue was incorrectly labeled as being LOE: 1 day, but unfortunately this is a little more complicated that what can be done in a day.

**Comment by jkleinsc** [comment]
I am going to tackle this one.
