### ISSUE TITLE
Build acceptance test for medication.search

### ISSUE THREAD

**Issue by billybonks** [HospitalRun/hospitalrun-frontend#698]
In order to effectively use the no missing translations test, we need to make sure that every page is visited during acceptance tests.

This issue tracks the missing `medication.search` acceptance test

for ember new commers the value `some.route` is the route that's missing you can find them under router.js

**Comment by remotevision** [comment]
I can work on this.

**Comment by jkleinsc** [comment]
@remotevision it's yours. Thanks for contributing!

**Comment by tangollama** [comment]
@remotevision, any progress here? I ask b/c we're getting close to a 1.0 beta release.

**Comment by richiethomas** [comment]
I can take a crack at this.  In order for the `no missing translations` test to be used effectively, is it necessary to test the exact-match `/medication/search/` in the acceptance tests?  Or is it acceptable to test a path like `/medication/search/:searchstring`?  The reason I ask is because the first example doesn't appear to be a valid URL in my browser, i.e. the path only works if a search string is appended.

**Comment by nzidol** [comment]
Note that the actual search function does not seem to work at the moment...
