### ISSUE TITLE
Build acceptance test for print.index

### ISSUE THREAD

**Issue by billybonks** [HospitalRun/hospitalrun-frontend#702]
In order to effectively use the no missing translations test, we need to make sure that every page is visited during acceptance tests.

This issue tracks the missing `print.index` acceptance test

for ember new commers the value `some.route` is the route that's missing you can find them under router.js

**Comment by billybonks** [comment]
@jkleinsc i think this route is never visited so we can close this ?

**Comment by jkleinsc** [comment]
@billybonks yes... though should we remove it from router.js in order to make sure your testing for untested routes works?

**Comment by richiethomas** [comment]
@jkleinsc while I was researching this issue, it became apparent that Ember renders the `index` route by default and that there is no way to disable this behavior (that I could find).  Is it possible to exempt this route from the `missing translations` test?  Or alternately, could we visit that index route (and any other unused index routes) in a separate test file that exists simply to satisfy the requirements of the `translations` test?  I'm just spitballing here, I know it's not an ideal solution.

Also, since my ember tests all pass on my local, I'm guessing the `missing translation` test is not included when running the default `ember test` command.  How could I run this test on my local?

**Comment by jkleinsc** [comment]
@richiethomas thanks for looking into this.  The test for missing translations was never created.  Also, you are correct that we can't remove the index route.  The test (when written) can be setup to ignore unused routes.  Therefore, I am going to close this issue.
