### ISSUE TITLE
Show user even when add new user is cancel

### ISSUE THREAD

**Issue by dinhvle** [HospitalRun/hospitalrun-frontend#719]
**Expected behavior:**
Should not show user when add user is cancel

**Actual behavior:**
User is being shown even if you cancel add user

**Steps to reproduce:**
1. Run HR locally with CouchDB v1.6.1
2. Log in as System Administrator
3. Go to Administrator > Users
4. Click + new user and cancel it
5. See a new user from User Listing

**Screenshots (if applicable):**
![screen shot 2016-10-10 at 11 39 15 am](https://cloud.githubusercontent.com/assets/13881061/19243771/a4b0bc5c-8ede-11e6-8916-cbfae4e35088.png)

**OS and Browser:**
OS X 10.11.6
Chrome Version 53.0.2785.143 (64-bit)

**Comment by kartik95** [comment]
Hi, I would like to take up this issue. @tangollama

**Comment by jkleinsc** [comment]
@kartik95 It's yours.  Thanks for pitching in!

**Comment by kartik95** [comment]
I have a doubt, siince documentation is not present in each file (which I would strongly recommend to have). In the 'edit-panel.hbs' component, what is the difference between cancelButtonText and cancel? Anyways, both are performing the same action 'cancel'. 

![screenshot from 2016-10-12 17 27 27](https://cloud.githubusercontent.com/assets/7141290/19309292/a09a6f5e-90a1-11e6-8e7e-588a93c0327e.png)

Also, can anyone make me go through the workflow? It is kind of difficult to get it without the documentation.

**Comment by gnowoel** [comment]
@kartik95 Perhaps we could fix the problem in either of the two ways:

* only displaying the persistent records in the `index` action, or
* pruning unsaved records when leaving the `new` action.

My personal preference is the latter, which is removing the unsaved new records. But I can be wrong since I'm also new to Ember.

**Comment by jkleinsc** [comment]
@kartik95 the reason for the two is that you can override what text appears for the cancel button on an edit screen by setting the cancelButtonText in your controller.  In the case of the edit controller for the user edit screen, it is extending app/controllers/abstract-edit-controller which defines cancelButtonText as a computed property that displays either Cancel or Return depending on the state of the data model.

As far as this issue is concerned, I took a look at it and it turns out it is an issue with a with edit-panel component.  I'll unpack it below.

**Comment by jkleinsc** [comment]
@kartik95  So here is what is happening.  I'll try to go into some detail, so forgive me if some of this information is obvious.  The user edit route is defined here:
https://github.com/HospitalRun/hospitalrun-frontend/tree/master/app/users/edit

If you take a look at the template for this route:
https://github.com/HospitalRun/hospitalrun-frontend/blob/master/app/users/edit/template.hbs

You will see that the whole thing is wrapped in a component, `edit-panel`.  That component defines the buttons and corresponding actions to fire when clicking on those buttons.  So if we look at the code for the edit-panel component here: https://github.com/HospitalRun/hospitalrun-frontend/blob/master/app/components/edit-panel.js
Here is the code for the cancel action:
```javascript
    cancel: function() {
      this.sendAction('editPanelProps.cancelAction');
    },
```
So what ends up happening is that editPanelProps.cancelAction fires - but what is that?  
It turns out that the controller for the user edit/add extends:
https://github.com/HospitalRun/hospitalrun-frontend/blob/master/app/controllers/abstract-edit-controller.js
That controller includes a mixin: 
https://github.com/HospitalRun/hospitalrun-frontend/blob/master/app/mixins/edit-panel-props.js
This mixin basically pulls attributes off of the controller and packages them up in an object to pass along to the edit-panel component.

The abstract-edit-controller defines cancelAction as `cancelAction: 'allItems',` and that is what ends up getting passed along to the edit-panel component.  `allItems` goes back to the index page, but the problem is a rollback on the model should happen before that action fires.  It turns out that the abstract-edit-controller has an action `cancel` that does this rollback and then calls the cancelAction, which is what should be called instead of `allItems`
https://github.com/HospitalRun/hospitalrun-frontend/blob/master/app/controllers/abstract-edit-controller.js#L85
At the root of the problem here is the overloading of `cancelAction`.  The edit-panel component really shouldn't pull in the cancelAction from editPanelProps and in fact editPanelProps shouldn't carry cancelAction in it at all.  I'll add another comment with the TLDR changes required.

**Comment by jkleinsc** [comment]
@kartik95 Here is the TLDR of what needs to be fixed here:
1) In https://github.com/HospitalRun/hospitalrun-frontend/blob/master/app/components/edit-panel.js
   a) Add the following here: https://github.com/HospitalRun/hospitalrun-frontend/blob/master/app/components/edit-panel.js#L3:
```javascript
  cancelAction: 'cancel',
```
   b) Change https://github.com/HospitalRun/hospitalrun-frontend/blob/master/app/components/edit-panel.js#L7 to:
```javascript
this.sendAction('cancelAction');
```
2) In https://github.com/HospitalRun/hospitalrun-frontend/blob/master/app/mixins/edit-panel-props.js all references to `cancelAction` should be removed (lines 5, 17, 27).

Let me know if this makes sense

**Comment by kartik95** [comment]
You pretty much explained the whole issue. Thanks a lot :smile: 
I'll get to it. Also, will this issue carry a 'Hacktoberfest' label?

**Comment by kartik95** [comment]
Fixed the bug. PR #729

**Comment by jkleinsc** [comment]
@kartik95 thanks for contributing.  I added the hacktoberfest label.
