### ISSUE TITLE
Appointment by default shouldn't be 'all day' 

### ISSUE THREAD

**Issue by marcorosas1991** [HospitalRun/hospitalrun-frontend#831]
**Expected behavior:**
The 'all day' option should not be ticked by default. Most of the time appointments have a defined length.

**Actual behavior:**
The 'all day' option is ticked when the new appointment form is open.

**Steps to reproduce:**
Click Appointments > + add appointment.
See 'all day' option.

**Screenshots (if applicable):**
<img width="1147" alt="screen shot 2016-11-30 at 9 20 15 pm" src="https://cloud.githubusercontent.com/assets/5996255/20781871/f16069ca-b743-11e6-88bf-db1d4b9d1b2d.png">

**OS and Browser:**
Chrome Version 54.0.2840.98 (64-bit)
MacOS 10.12.1

**Comment by jkleinsc** [comment]
@marcorosas1991 I think it depends upon context/preference.  In some use cases the desired default will be all day appointments; in other cases exact times will be needed.  The only thing I would suggest is an enhancement to allow this to be configurable.

**Comment by jkleinsc** [comment]
@marcorosas1991 I was looking at something with appointments and I realized something:
I think the intention was that All Day would be on for Admission type appointments and off for other types of appointments, but I think this line was incorrectly coded:
https://github.com/HospitalRun/hospitalrun-frontend/blob/master/app/appointments/edit/controller.js#L76

**Comment by mqchau** [comment]
I plan to revamp that function isAdmissionAppointment because it is causing a bug on appointment edit page. That bug was raised in #815. Maybe after that it solves this issue too.

**Comment by jkleinsc** [comment]
@mqchau I don't mind if you take a look at this, but right now I am tackling an issue in appointments caused by the migration to Ember 2.10 - unless you already have a solution for this problem!  Basically what I am seeing is that there are some observers in https://github.com/HospitalRun/hospitalrun-frontend/blob/master/app/appointments/edit/controller.js that don't play well with Ember 2.10.  That code is used for appointments that are not multi day (eg anything but an Admission type visit).  Those types of appointments are just supposed to display one date field and separate fields for start time and end time.  I believe the solution is to move this logic/markup to a component.

**Comment by jkleinsc** [comment]
@mqchau I ended fixing this a part of my refactor.
