### ISSUE TITLE
Users module doesn't work with CouchDB 2.0

### ISSUE THREAD

**Issue by jkleinsc** [HospitalRun/hospitalrun-frontend#953]
**Expected behavior:**
All functionality of the Users module should work with CouchDB 2.0
**Actual behavior:**
When a user who has admin rights navigates to the users module, they are redirected to login.
**Steps to reproduce:**
Setup HospitalRun to use CouchDB 2.0
Navigate to the Users module
**Screenshots (if applicable):**
N/A
**OS and Browser:**
All

**Comment by adeolabadmus** [comment]
The issue seems to be caused by this line in the [documentation](http://docs.couchdb.org/en/2.0.0/intro/security.html#authentication-database): `Only administrators may browse list of all documents (GET /_users/_all_docs)` which is clearly not the case in CouchDB 1.6.

The `admin/users` route makes an API call to fetch all users in the database: https://github.com/HospitalRun/hospitalrun-frontend/blob/master/app/adapters/user.js#L170. Since the currently logged-in user is not a CouchDB administrator, the call returns a 401 error response, which in turn logs the user out.

In 2.0, Only administrator accounts can successfully make such calls. I do not see any way to authenticate login using the administrator credentials since they are stored in the config file, and not in the `_users` database.

**Comment by jkleinsc** [comment]
@adeolabadmus the 1.6 documentation says the same thing.  I am talking to Jan Lehnardt of CouchDB about the issue.  He thinks it is something they missed porting over.

**Comment by innopage** [comment]
I think I'm hitting this bug / issue even though I used CouchDB 1.6 in my docker compose.....any ideas how to work around this please?

**Comment by sachin8778** [comment]
Hi, I am also facing this issue with CouchDB 1.6 and HospitalRun 1.0.0-beta. However this issue is not showing in HospitalRun 0.9.8 after downgrading to CouchDB 1.6, that combination is running fine.

**Comment by sachin8778** [comment]
ok, after adding "hradmin" & "test" into couchdb as admin problem resolved for now. But there should be real solution to this for production use.

**Comment by waleplanet** [comment]
after adding "hradmin" and test into "couchdb" 1.6 i still get redirected to login

**Comment by LOKANADHAN** [comment]
Name or password is incorrect. in Project Fauxton

**Comment by LOKANADHAN** [comment]
Username: hradmin and password: test

**Comment by adeolabadmus** [comment]
Hello @fox1t. I see you closed this issue. Has it been fixed?

**Comment by fox1t** [comment]
Hi @adeolabadmus! 
We're [now working on a new major version](https://github.com/HospitalRun/hospitalrun-frontend/issues/1605#issuecomment-518749445) (2.0) of HospitalRun. Sadly, this issue won't be resolved and we're forced to close this issue. 
Can you contribute to the project? If so ping me on [slack](hospitalrun.slack.com) since we will need a big community effort to build the best HIS!
